#ifndef VERSION_H
#define VERSION_H

// 自动生成的版本信息，请勿手动修改
#define PROJECT_NAME        "@PROJECT_NAME@"
#define VERSION_MAJOR       @VERSION_MAJOR@
#define VERSION_MINOR       @VERSION_MINOR@
#define VERSION_PATCH       @VERSION_PATCH@
#define VERSION_BUILD       @VERSION_BUILD@

#define GIT_COMMIT_HASH     "@GIT_HASH@"
#define GIT_BRANCH          "@GIT_BRANCH@"
#define BUILD_TIMESTAMP     "@BUILD_TIME@"

#define VERSION_STRING      "@VERSION_MAJOR@.@VERSION_MINOR@.@VERSION_PATCH@.@VERSION_BUILD@"
#define FULL_VERSION_STRING "@VERSION_MAJOR@.@VERSION_MINOR@.@VERSION_PATCH@ (@GIT_BRANCH@ - @GIT_HASH@)"

#endif // VERSION_H
